#!/usr/bin/env bash
# Usage: git psu [REMOTE]
# Pushes the current branch and sets the given remote as upstream.
# v1.6.0

REMOTE=origin

if (( $# > 0 )); then
  REMOTE=${1##*=}
fi

git push -u "$REMOTE" "$(git rev-parse --abbrev-ref HEAD)"
