.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "GIT\-PSU" "1" "February 2018" "" ""
.
.SH "NAME"
\fBgit\-psu\fR \- Push the current branch and set as default upstream.
.
.SH "SYNOPSIS"
\fBgit psu\fR [REMOTE]
.
.SH "DESCRIPTION"
\fBgit\-psu\fR Push the current branch and sets the given remote as upstream\.
.
.SH "SEE ALSO"
git(1), git-push(1)
