#!/usr/bin/env bash
# Usage: git fixup [BRANCH]
# Allows the selection of a commit to be used with `rebase --autosquash`.
# v1.4.0

# TODO: completion for branches.

# Quit when there's an error.
set -e

# Use the first argument as branch or fallback to the configuration or to the
# default value.
if [[ -n "$1" ]]; then
  BRANCH="$1"
else
  BRANCH=$(git config --get 'fixup.branch' || echo 'origin/master')
fi

# Pick from those commits.
# TODO: Make the picker configurable.
sha1=$(git log $BRANCH..HEAD --pretty=format:'%H' | fzf --preview='git show {}')

# Commit!
git commit --fixup=$sha1
