#!/usr/bin/env bash
# Usage: git wip [-m MESSAGE] [FILES]
# Generates a git commit with the given message, prefixed by "[WIP]"
# v1.0.0

set -e

function usage() {
  echo "Usage: git wip [-m MESSAGE] [FILES]"
  exit 1
}

# Parse command line arguments.
while getopts ":hm:" opt; do
  case ${opt} in
    h )
      usage
      ;;
    \? )
      usage
      ;;
    m )
      MESSAGE=$OPTARG
      ;;
    : )
      echo "git-wip: error switch \`m' requires a value." 1>&2
      usage
      ;;
  esac
done
shift $((OPTIND -1))

FILES=${*:-.}

if [[ -z $MESSAGE ]]; then
  MESSAGE="[WIP]"
else
  MESSAGE="[WIP] $MESSAGE"
fi

git add "$FILES" && git commit -m "$MESSAGE"
