.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "GIT\-EXCLUDE" "1" "February 2018" "" ""
.
.SH "NAME"
\fBgit\-exclude\fR \- Locally exclude patterns
.
.SH "SYNOPSIS"
\fBgit exclude\fR PATTERN
.
.SH "DESCRIPTION"
\fBgit\-exclude\fR locally excludes pattern from the git index\.
.
.SH "SEE ALSO"
git(1), gitignore(5)
